name: cartoons553 # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '2.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A program that renders blender projects. # 79 char long summary
description: |
  cartoons553 renders blender projects on Google Cloud.
  You can pick any machine size you want.
  And it would download the render output for you.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go


apps:
  cartoons553:
    command: bin/cartoons553
    plugs:
      - network
